use serde::{Deserialize, Serialize};

/// Strategy rule types
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum RuleType {
    /// Adjust SL/TP based on volatility (ATR)
    VolatilitySlTp,
    /// Dynamic position sizing (Kelly, confidence-weighted)
    PositionSizing,
    /// Filter by signal confidence threshold
    ConfidenceFilter,
    /// Blacklist/whitelist coins
    CoinFilter,
    /// Scale leverage based on conditions
    LeverageScale,
    /// Trading session restrictions
    SessionFilter,
    /// Rules generated by Lesson Engine
    LessonRule,
}

/// Market regime detection
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum MarketRegime {
    Trending,
    Ranging,
    Volatile,
    Unknown,
}

/// Trading session
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum TradingSession {
    Asia,    // 00:00 - 08:00 UTC
    Europe,  // 08:00 - 16:00 UTC
    Us,      // 16:00 - 24:00 UTC
}

impl TradingSession {
    pub fn current() -> Self {
        let hour = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_secs()
            % 86400
            / 3600;

        match hour {
            0..=7 => Self::Asia,
            8..=15 => Self::Europe,
            _ => Self::Us,
        }
    }

    pub fn as_str(&self) -> &str {
        match self {
            Self::Asia => "asia",
            Self::Europe => "europe",
            Self::Us => "us",
        }
    }
}

/// A strategy rule stored in DB
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StrategyRule {
    pub id: i64,
    pub name: String,
    pub rule_type: RuleType,
    pub conditions: serde_json::Value,
    pub action: serde_json::Value,
    pub priority: i32,
    pub active: bool,
    pub source: String, // "default" or "lesson"
    pub hit_count: i64,
}

/// Output of Strategy Engine evaluation
#[derive(Debug, Clone)]
pub struct StrategyParams {
    /// Should we execute this trade?
    pub should_execute: bool,
    /// Position size multiplier (0.0 - 2.0)
    pub size_multiplier: f64,
    /// Adjusted leverage
    pub leverage: u32,
    /// Adjusted stop loss percentage
    pub stop_loss_pct: f64,
    /// Adjusted take profit percentage
    pub take_profit_pct: f64,
    /// Confidence threshold (skip if below)
    pub confidence_threshold: f64,
    /// Reason for adjustments
    pub reasons: Vec<String>,
}

impl StrategyParams {
    /// Default params from config (no adjustments)
    pub fn from_config(
        max_leverage: u32,
        stop_loss_pct: f64,
        take_profit_pct: f64,
    ) -> Self {
        Self {
            should_execute: true,
            size_multiplier: 1.0,
            leverage: max_leverage,
            stop_loss_pct,
            take_profit_pct,
            confidence_threshold: 0.5,
            reasons: Vec::new(),
        }
    }

    pub fn add_reason(&mut self, reason: String) {
        self.reasons.push(reason);
    }

    pub fn reasons_summary(&self) -> String {
        if self.reasons.is_empty() {
            "no adjustments".to_string()
        } else {
            self.reasons.join("; ")
        }
    }
}

/// Calculate Simple Moving Average from price series
pub fn calc_sma(prices: &[f64]) -> f64 {
    if prices.is_empty() {
        return 0.0;
    }
    prices.iter().sum::<f64>() / prices.len() as f64
}

/// Calculate Average True Range (simplified — using price changes)
pub fn calc_atr_pct(prices: &[f64]) -> f64 {
    if prices.len() < 2 {
        return 0.0;
    }

    let mut changes = Vec::new();
    for i in 1..prices.len() {
        let change = (prices[i] - prices[i - 1]).abs() / prices[i - 1] * 100.0;
        changes.push(change);
    }

    changes.iter().sum::<f64>() / changes.len() as f64
}

/// Detect market regime from price data
pub fn detect_regime(prices: &[f64]) -> MarketRegime {
    if prices.len() < 5 {
        return MarketRegime::Unknown;
    }

    let atr = calc_atr_pct(prices);
    let sma = calc_sma(prices);
    let last = *prices.last().unwrap();

    // Check trend direction consistency
    let mut up_moves = 0;
    let mut down_moves = 0;
    for i in 1..prices.len() {
        if prices[i] > prices[i - 1] {
            up_moves += 1;
        } else {
            down_moves += 1;
        }
    }

    let trend_strength = (up_moves as f64 - down_moves as f64).abs() / prices.len() as f64;

    if atr > 3.0 {
        MarketRegime::Volatile
    } else if trend_strength > 0.6 && (last - sma).abs() / sma > 0.02 {
        MarketRegime::Trending
    } else {
        MarketRegime::Ranging
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_strategy_params_default() {
        let params = StrategyParams::from_config(20, 1.5, 3.0);
        assert!(params.should_execute);
        assert_eq!(params.size_multiplier, 1.0);
        assert_eq!(params.leverage, 20);
        assert_eq!(params.stop_loss_pct, 1.5);
        assert_eq!(params.take_profit_pct, 3.0);
        assert_eq!(params.confidence_threshold, 0.5);
    }

    #[test]
    fn test_calc_sma() {
        let prices = vec![100.0, 110.0, 120.0];
        assert!((calc_sma(&prices) - 110.0).abs() < 0.01);
    }

    #[test]
    fn test_calc_atr_pct_low() {
        // Low volatility — small changes
        let prices = vec![100.0, 100.5, 100.3, 100.8, 100.6];
        let atr = calc_atr_pct(&prices);
        assert!(atr < 1.0);
    }

    #[test]
    fn test_calc_atr_pct_high() {
        // High volatility — large changes
        let prices = vec![100.0, 105.0, 98.0, 108.0, 95.0];
        let atr = calc_atr_pct(&prices);
        assert!(atr > 3.0);
    }

    #[test]
    fn test_detect_regime_volatile() {
        let prices = vec![100.0, 108.0, 95.0, 110.0, 92.0, 112.0];
        assert_eq!(detect_regime(&prices), MarketRegime::Volatile);
    }

    #[test]
    fn test_detect_regime_trending() {
        // Consistent uptrend
        let prices = vec![100.0, 102.0, 105.0, 108.0, 112.0, 115.0, 118.0, 120.0];
        let regime = detect_regime(&prices);
        assert!(regime == MarketRegime::Trending || regime == MarketRegime::Ranging);
    }

    #[test]
    fn test_trading_session() {
        // Just test it doesn't panic
        let session = TradingSession::current();
        assert!(!session.as_str().is_empty());
    }

    #[test]
    fn test_rule_type_serde() {
        let rule_type = RuleType::VolatilitySlTp;
        let json = serde_json::to_string(&rule_type).unwrap();
        let back: RuleType = serde_json::from_str(&json).unwrap();
        assert_eq!(rule_type, back);
    }
}
