use chrono::{Timelike, Utc};
use log::{debug, info};

use crate::config::FilterConfig;
use crate::funding::FundingMonitor;
use crate::orderbook::OrderbookAnalyzer;
use crate::orderflow::OrderflowAnalyzer;
use crate::ta::TaEngine;

/// Signal direction
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum SignalDirection {
    Long,
    Short,
}

/// Trading signal generated by the decision engine
#[derive(Debug, Clone)]
pub struct Signal {
    pub pair: String,
    pub direction: SignalDirection,
    pub score: u32,
    pub ema9: f64,
    pub ema21: f64,
    pub rsi: f64,
    pub atr: f64,
    pub atr_pct: f64,
    pub spread_bps: f64,
    pub imbalance: f64,
    pub cvd: f64,
    pub funding_rate: f64,
    pub in_session: bool,
}

/// Decision engine — 7-step rule-based signal evaluation
pub struct DecisionEngine {
    min_score: u32,
    max_spread_bps: f64,
    min_imbalance: f64,
    max_imbalance: f64,
    min_depth_usd: f64,
    filters: FilterConfig,
}

impl DecisionEngine {
    pub fn new(
        min_score: u32,
        max_spread_bps: f64,
        min_imbalance: f64,
        max_imbalance: f64,
        min_depth_usd: f64,
        filters: FilterConfig,
    ) -> Self {
        Self {
            min_score,
            max_spread_bps,
            min_imbalance,
            max_imbalance,
            min_depth_usd,
            filters,
        }
    }

    /// Check if current time is within preferred trading session
    /// Supports wrap-around sessions (e.g., 22-6 means 22:00-06:00 UTC)
    fn in_preferred_session(&self) -> bool {
        let hour = Utc::now().hour();
        if self.filters.session_start_utc <= self.filters.session_end_utc {
            // Normal range: e.g., 13-21
            hour >= self.filters.session_start_utc && hour <= self.filters.session_end_utc
        } else {
            // Wrap-around: e.g., 22-6 means 22:00-05:59
            hour >= self.filters.session_start_utc || hour <= self.filters.session_end_utc
        }
    }

    /// Evaluate signal for a pair through 7 steps
    pub fn evaluate_signal(
        &self,
        pair: &str,
        orderbook: &OrderbookAnalyzer,
        orderflow: &OrderflowAnalyzer,
        funding: &FundingMonitor,
        ta: &TaEngine,
    ) -> Option<Signal> {
        // ========== Step 1: Liquidity Filter (Orderbook) ==========
        let spread_bps = orderbook.spread_bps()?;
        if spread_bps > self.max_spread_bps {
            info!("{}: REJECT spread {:.2} bps > {}", pair, spread_bps, self.max_spread_bps);
            return None;
        }

        let imbalance = orderbook.imbalance_ratio()?;
        if imbalance < self.min_imbalance || imbalance > self.max_imbalance {
            info!("{}: REJECT imbalance {:.3} outside [{}, {}]", pair, imbalance, self.min_imbalance, self.max_imbalance);
            return None;
        }

        let depth_l1 = orderbook.depth_usd_level1()?;
        if depth_l1 < self.min_depth_usd {
            info!("{}: REJECT depth_l1 ${:.0} < ${:.0}", pair, depth_l1, self.min_depth_usd);
            return None;
        }
        debug!("{}: Step1 OK — spread={:.2}bps imb={:.3} depth=${:.0}", pair, spread_bps, imbalance, depth_l1);

        // ========== Step 2: ATR Volatility Filter ==========
        let atr = ta.atr14()?;
        let atr_pct = ta.atr_pct()?;

        if atr_pct > self.filters.max_atr_pct {
            info!("{}: REJECT ATR {:.2}% > max {:.1}% (terlalu volatile)", pair, atr_pct, self.filters.max_atr_pct);
            return None;
        }
        if atr_pct < self.filters.min_atr_pct {
            info!("{}: REJECT ATR {:.3}% < min {:.2}% (terlalu sepi)", pair, atr_pct, self.filters.min_atr_pct);
            return None;
        }
        debug!("{}: Step2 OK — ATR={:.4} ({:.2}%)", pair, atr, atr_pct);

        // ========== Step 3: Technical Filter (EMA + RSI) ==========
        let ema9 = ta.ema9()?;
        let ema21 = ta.ema21()?;
        let rsi = ta.rsi14()?;
        let latest_close = ta.latest_close()?;

        let direction = if ema9 > ema21 {
            SignalDirection::Long
        } else if ema9 < ema21 {
            SignalDirection::Short
        } else {
            debug!("{}: REJECT EMA9 == EMA21", pair);
            return None;
        };

        if rsi <= 30.0 || rsi >= 70.0 {
            info!("{}: REJECT RSI {:.1} outside [30,70]", pair, rsi);
            return None;
        }
        debug!("{}: Step3 OK — dir={:?} EMA9={:.2} EMA21={:.2} RSI={:.1}", pair, direction, ema9, ema21, rsi);

        // ========== Step 4: Funding Filter (per direction) ==========
        let funding_rate = match funding.get_rate(pair) {
            Some(rate) => rate,
            None => {
                debug!("{}: No funding data available, using 0.0", pair);
                0.0
            }
        };
        match direction {
            SignalDirection::Long => {
                if funding.is_funding_too_high_for_long(pair) {
                    info!("{}: REJECT funding too high for LONG", pair);
                    return None;
                }
            }
            SignalDirection::Short => {
                if funding.is_funding_too_high_for_short(pair) {
                    info!("{}: REJECT funding too negative for SHORT", pair);
                    return None;
                }
            }
        }
        debug!("{}: Step4 OK — funding={:.4}%", pair, funding_rate * 100.0);

        // ========== Step 5: Order Flow (CVD) ==========
        let cvd = orderflow.get_cvd(pair);
        let price_trend_up = latest_close > ema21;

        if orderflow.is_cvd_diverging(pair, price_trend_up) {
            info!("{}: REJECT CVD diverging (cvd={:.2})", pair, cvd);
            return None;
        }

        let cvd_confirms = match direction {
            SignalDirection::Long => cvd > 0.0,
            SignalDirection::Short => cvd < 0.0,
        };
        debug!("{}: Step5 OK — CVD={:.2} confirms={}", pair, cvd, cvd_confirms);

        // ========== Step 6: Session Filter ==========
        let in_session = self.in_preferred_session();
        debug!("{}: Step6 — in_session={}", pair, in_session);

        // ========== Step 7: Composite Score ==========
        let mut score: u32 = 60; // TA passed
        if cvd_confirms { score += 20; }
        // Funding already passed (Step 4 rejects if adverse), so no extra score
        // Real score range: 60 (no CVD) to 80 (CVD confirms)

        // Session penalty — kurangi score di luar NY session
        if self.filters.session_filter_enabled && !in_session {
            score = score.saturating_sub(self.filters.session_penalty);
            debug!("{}: Session penalty -{} (outside NY hours)", pair, self.filters.session_penalty);
        }

        if score < self.min_score {
            info!("{}: REJECT score {} < {}", pair, score, self.min_score);
            return None;
        }

        info!(
            "{}: SIGNAL {:?} score={} EMA9={:.2} EMA21={:.2} RSI={:.1} CVD={:.2} ATR={:.2}% session={}",
            pair, direction, score, ema9, ema21, rsi, cvd, atr_pct, in_session
        );

        Some(Signal {
            pair: pair.to_string(),
            direction,
            score,
            ema9,
            ema21,
            rsi,
            atr,
            atr_pct,
            spread_bps,
            imbalance,
            cvd,
            funding_rate,
            in_session,
        })
    }
}
